### PR TITLE
feat(#188): add http provider to provide readonly information.

### LINKED ISSUE #188: HTTP provider should be added to support non-wallet query
## Summary

Users should have a similar experience in some common query fields no matter whether their wallets are connected or not. To achieve this goal, an addition HTTP provider should be added to bypass the RPC providers like metamask which usually require wallet connected to continue following queries even if these queries do not need wallet information.

## Expected Behaviour

All queries which need no wallet information should be available no matter whether the wallet is connected. Other operations should be shown in a UX "disable" way to indicate a wallet connection is needed.

## Solution

Describe the solution you'd like.
If you have no idea pls just leave it blank.

### Alternative

Describe alternatives you've considered

## Roadmap

Maintainer could use this section to record issue roadmap.

### PR DESCRIPTION
**Pull request by SantanaSP**
resolve #188 .

### CODE REVIEW

**Comment by Erreth-Akbe** [comment]
Should we add BSC and polygon http provider at same time?
BSC documentation:
https://stackoverflow.com/questions/68327594/web3-providers-httpproviderhttps-bsc-dataseed-binance-org-connect-false
https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes

**Comment by SantanaSP** [comment]
> Should we add BSC and polygon http provider at same time? BSC documentation: https://stackoverflow.com/questions/68327594/web3-providers-httpproviderhttps-bsc-dataseed-binance-org-connect-false https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes

Yes, I'm adding them now

**Comment by SantanaSP** [comment]
Do we have our own polygon rpc server? @Erreth-Akbe

**Review by Erreth-Akbe — APPROVED** [review]

**Comment by Erreth-Akbe** [comment]
too poor to get a polygon rpc server.

**Pull request merged**
