### PR TITLE
Issue #87 - Customer need a Spark Page in PC client

### LINKED ISSUE #87: Customer need a Spark Page in PC client.
## Summary

For path `/art/NFTID` page, now customer and owner can access same page and display different componet.
But we should split this two pages for customer and owner. 
`/art` for owner, it will has download, recieve income model.

`/spark` for customer and this page's url will also be in `Link Share` and `Poster Share`. It will has Mint and Download model.

## Roadmap

- [x] [Art page UI/UX design] (https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=684%3A1375)
- [x] [Spark page UI/UX design] (https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=844%3A1375)
- [ ] [Art page] Coding
- [ ] [Spark page] Coding

## Validation

- [ ] As a customer, I can Mint a child node NFT at Spark Page, the jump to the art page for my new NFT node.
- [ ] Use the `Dialog` component in the components folder to display the processing information.

### PR DESCRIPTION
**Pull request by codeAtNow**
Resolve #87 .

### CODE REVIEW

**Comment by SantanaSP** [comment]
I click the "Link Sharing" button and it just write things into my clickboard. Should we just change how this button functions?

**Comment by SantanaSP** [comment]
> I click the "Link Sharing" button and it just write things into my clickboard. Should we just change how this button functions?

Wait a minute, its maybe my fault to misunderstand this button. I'll talk with PM to get things more clear.

**Comment by Erreth-Akbe** [comment]
That is the expected behavior. @SantanaSP

**Comment by SantanaSP** [comment]
Fine, I'll start review.

**Comment by SantanaSP** [comment]
The final page doesn't match the design draft. Below is design draft.

image

Below is PR version.

image

Please check whether **all of** your pages match the design draft.

**Comment by SantanaSP** [comment]
Reopen this PR when you have new commits.

**Comment by Erreth-Akbe** [comment]
@codeAtNow Have we coded `DownLoad featrue` at Spark page?

**Pull request closed without merging**
